import test from 'node:test';import assert from 'node:assert/strict';import{empty,apply,totals,due,balance,stock,validate,docTotal,projectStats}from'../src/domain.js';
const save=(s,t,d)=>apply(s,{type:'save',table:t,data:d});
function setup(){let s=empty();s=save(s,'clients',{id:'c',name:'Test'});s=save(s,'projects',{id:'p',name:'Chantier test',clientId:'c',budget:600000,contractAmount:1000000});s=save(s,'quotes',{id:'q',clientId:'c',projectId:'p',lines:[{description:'Travaux',quantity:2,unitPrice:500000}],tax:0});return s;}
test('parcours devis facture paiement dépense et solde',()=>{let s=apply(setup(),{type:'convert',id:'q'}),i=s.invoices[0];assert.equal(docTotal(i),1000000);assert.throws(()=>apply(s,{type:'convert',id:'q'}),/déjà/);s=apply(s,{type:'payment',data:{invoiceId:i.id,accountId:'main',amount:800000}});s=save(s,'expenses',{scope:'Chantier',projectId:'p',accountId:'main',description:'Achat',amount:200000});assert.equal(due(s,i),200000);assert.equal(totals(s).balance,600000);assert.equal(projectStats(s,'p').cost,200000);assert.equal(validate(s),s)});
test('transfert sans double recette ni double dépense',()=>{let s=save(setup(),'accounts',{id:'other',name:'Autre',opening:0});s=apply(s,{type:'cash',data:{accountId:'main',amount:500000,label:'Apport'}});let before=totals(s);s=apply(s,{type:'transfer',data:{fromId:'main',toId:'other',amount:100000}});assert.deepEqual(totals(s),before);assert.equal(balance(s,'main'),400000);assert.equal(balance(s,'other'),100000);assert.throws(()=>apply(s,{type:'transfer',data:{fromId:'main',toId:'other',amount:500000}}),/insuffisant/);assert.throws(()=>apply(s,{type:'transfer',data:{fromId:'main',toId:'main',amount:1}}),/différentes/)});
test('surpaiement et montants invalides refusés sans mutation',()=>{let s=apply(setup(),{type:'convert',id:'q'}),i=s.invoices[0],original=JSON.stringify(s);for(const n of [1000001,-1,0,Infinity,0.5])assert.throws(()=>apply(s,{type:'payment',data:{invoiceId:i.id,accountId:'main',amount:n}}));assert.equal(JSON.stringify(s),original)});
test('annulation paiement recalcule facture et caisse',()=>{let s=apply(setup(),{type:'convert',id:'q'}),i=s.invoices[0];s=apply(s,{type:'payment',data:{id:'pay',invoiceId:i.id,accountId:'main',amount:1000000}});assert.throws(()=>apply(s,{type:'void',table:'invoices',id:i.id,reason:'Test'}),/paiements/);s=apply(s,{type:'void',table:'payments',id:'pay',reason:'Erreur de saisie'});assert.equal(due(s,i),1000000);assert.equal(balance(s,'main'),0);assert.equal(s.payments.length,1)});
test('équipe : tâche liée au chantier et montant plafonné',()=>{let s=save(setup(),'employees',{id:'emp',name:'Ouvrier test'});s=save(s,'tasks',{id:'task',employeeId:'emp',projectId:'p',description:'Pose',agreedAmount:100000});s=apply(s,{type:'teamPayment',data:{taskId:'task',accountId:'main',amount:60000}});assert.equal(projectStats(s,'p').forecast,100000);assert.throws(()=>apply(s,{type:'teamPayment',data:{taskId:'task',accountId:'main',amount:50000}}),/dépasse/)});
test('stock : pas de sortie au-delà du disponible',()=>{let s=save(empty(),'materials',{id:'mat',description:'Panneau',opening:10,threshold:2,lastPrice:5000});s=apply(s,{type:'stock',data:{materialId:'mat',type:'Sortie',quantity:3}});assert.equal(stock(s,'mat'),7);assert.throws(()=>apply(s,{type:'stock',data:{materialId:'mat',type:'Sortie',quantity:8}}),/insuffisant/)});
test('échéances ne dépassent pas le montant facturé',()=>{let s=apply(setup(),{type:'convert',id:'q'});s=save(s,'schedules',{invoiceId:s.invoices[0].id,dueDate:'2026-10-20',amount:600000});assert.throws(()=>save(s,'schedules',{invoiceId:s.invoices[0].id,dueDate:'2026-10-25',amount:500000}),/dépassent/)});
test('sauvegarde invalide rejetée',()=>{assert.throws(()=>validate({}));let s=empty();s.accounts.push({...s.accounts[0]});assert.throws(()=>validate(s),/Identifiants/)});
test('création chantier après encaissement conserve le lien des paiements',()=>{let s=empty();s=save(s,'clients',{id:'c',name:'Test'});s=apply(s,{type:'invoice',data:{id:'i',clientId:'c',lines:[{description:'Travaux',quantity:1,unitPrice:100000}]}});s=apply(s,{type:'payment',data:{invoiceId:'i',accountId:'main',amount:50000}});s=apply(s,{type:'projectFromDocument',data:{id:'p',name:'Chantier',clientId:'c',budget:50000,contractAmount:100000,sourceId:'i',sourceTable:'invoices'}});assert.equal(s.invoices[0].projectId,'p');assert.equal(projectStats(s,'p').received,50000);assert.equal(totals(s).balance,50000)});
test('double soumission paiement refusée',()=>{let s=apply(setup(),{type:'convert',id:'q'});const a={type:'payment',data:{id:'unique',invoiceId:s.invoices[0].id,accountId:'main',amount:10}};s=apply(s,a);assert.throws(()=>apply(s,a),/déjà enregistrée/)});
