export const TABLES=['clients','projects','quotes','invoices','payments','expenses','employees','tasks','teamPayments','suppliers','materials','stockMoves','orders','deliveries','journal','accounts','transfers','cashEntries','schedules','attachments','audit'];
export const today=()=>new Date().toISOString().slice(0,10);
export const uid=()=>crypto.randomUUID?crypto.randomUUID():Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');
export const money=n=>new Intl.NumberFormat('fr-FR').format(Math.round(Number(n)||0))+' F';
export function empty(){return {schema:3,app:'GBA Gestion Web',settings:{company:'GÉNÉRALE BTP AFRIQUE',address:'Bamako, Mali',phone:'+223 77 67 03 03',email:'contact@gbafrique.com',website:'gbafrique.com',tax:0,quotePrefix:'GBA-D',invoicePrefix:'GBA-F',receiptPrefix:'GBA-R',terms:'',footer:'Construire aujourd’hui • Bâtir demain • Développer l’Afrique'},...Object.fromEntries(TABLES.map(t=>[t,[]])),accounts:[{id:'main',name:'Caisse entreprise',opening:0}]};}
export const find=(s,t,id)=>s[t].find(x=>String(x.id)===String(id));
export const sum=(a,key='amount')=>a.reduce((n,r)=>n+(Number(r[key])||0),0);
export const active=a=>a.filter(x=>!x.void);
export function lineTotal(lines){return Math.round(lines.reduce((n,l)=>n+Number(l.quantity)*Number(l.unitPrice),0));}
export function docTotal(d){let ht=lineTotal(d.lines||[]);return Math.round((ht-(Number(d.discount)||0))*(1+(Number(d.tax)||0)/100));}
export function paid(s,id){return sum(active(s.payments).filter(p=>p.invoiceId===id));}
export function due(s,i){return i.void?0:Math.max(0,docTotal(i)-paid(s,i.id));}
export function balance(s,id){const a=find(s,'accounts',id);return (Number(a?.opening)||0)+sum(active(s.payments).filter(x=>x.accountId===id))+sum(active(s.cashEntries).filter(x=>x.accountId===id))-sum(active(s.expenses).filter(x=>x.accountId===id))-sum(active(s.teamPayments).filter(x=>x.accountId===id))+sum(active(s.transfers).filter(x=>x.toId===id))-sum(active(s.transfers).filter(x=>x.fromId===id));}
export function totals(s){return {balance:sum(s.accounts.map(x=>({amount:balance(s,x.id)}))),incoming:sum(active(s.payments))+sum(active(s.cashEntries).filter(x=>x.amount>0)),outgoing:sum(active(s.expenses))+sum(active(s.teamPayments))-sum(active(s.cashEntries).filter(x=>x.amount<0)),due:s.invoices.reduce((n,i)=>n+due(s,i),0),invoiced:active(s.invoices).reduce((n,i)=>n+docTotal(i),0)};}
export function projectStats(s,id){let p=find(s,'projects',id),expense=sum(active(s.expenses).filter(x=>x.projectId===id)),team=sum(active(s.teamPayments).filter(x=>x.projectId===id)),committed=sum(s.tasks.filter(x=>x.projectId===id),'agreedAmount'),invoices=active(s.invoices).filter(x=>x.projectId===id),billed=invoices.reduce((n,i)=>n+docTotal(i),0),received=sum(active(s.payments).filter(x=>x.projectId===id));return {expense,team,committed,cost:expense+team,forecast:expense+Math.max(team,committed),received,billed,due:invoices.reduce((n,i)=>n+due(s,i),0),margin:(p.contractAmount||billed)-expense-Math.max(team,committed),budget:p.budget||0};}
export const stock=(s,id)=>(Number(find(s,'materials',id)?.opening)||0)+s.stockMoves.filter(x=>x.materialId===id).reduce((n,x)=>n+(x.type==='Entrée'?1:-1)*Number(x.quantity),0);
export function nextNumber(s,table,prefix){const year=today().slice(0,4),base=prefix+'-'+year+'-';let max=s[table].reduce((n,x)=>{const v=x.number||'';return v.startsWith(base)?Math.max(n,Number(v.slice(base.length))||0):n},0);return base+String(max+1).padStart(3,'0');}
const assert=(c,m)=>{if(!c)throw Error(m)};
const amount=n=>assert(Number.isSafeInteger(Number(n))&&Number(n)>0,'Le montant doit être un entier positif en FCFA.');
const ref=(s,t,id,label)=>assert(!!find(s,t,id),label+' introuvable.');
function docCheck(s,d){ref(s,'clients',d.clientId,'Client');if(d.projectId){ref(s,'projects',d.projectId,'Chantier');assert(find(s,'projects',d.projectId).clientId===d.clientId,'Le chantier doit appartenir au client choisi.');}assert(d.lines?.length>0,'Ajoutez une prestation.');d.lines.forEach(l=>{assert(l.description?.trim(),'Désignation obligatoire.');assert(Number(l.quantity)>0&&Number.isFinite(Number(l.quantity)),'Quantité invalide.');assert(Number.isSafeInteger(Number(l.unitPrice))&&Number(l.unitPrice)>=0,'Prix unitaire invalide.');});assert(Number(d.discount||0)>=0&&Number(d.discount||0)<=lineTotal(d.lines),'Remise invalide.');assert(Number(d.tax||0)>=0&&Number(d.tax||0)<=100,'TVA invalide.');amount(docTotal(d));}
export function apply(state,action){const s=structuredClone(state),{type,table,data={}}=action;let id=data.id||uid();
 if(['payment','teamPayment','transfer','cash','stock','delivery','invoice'].includes(type)){const target=({payment:'payments',teamPayment:'teamPayments',transfer:'transfers',cash:'cashEntries',stock:'stockMoves',delivery:'deliveries',invoice:'invoices'})[type];assert(!find(s,target,id),'Cette opération est déjà enregistrée.');}
 if(type==='save'){
 assert(TABLES.includes(table)&&!['audit','payments','teamPayments','transfers','stockMoves','cashEntries','invoices','deliveries'].includes(table),'Opération invalide.');
 const d={...data,id};
 if(['clients','projects','employees','suppliers','accounts'].includes(table))assert(d.name?.trim(),'Le nom est obligatoire.');
 if(table==='accounts'){assert(Number.isSafeInteger(Number(d.opening)),'Solde initial invalide.');if(find(s,table,id))assert(Number(find(s,table,id).opening)===Number(d.opening),'Le solde initial est figé. Utilisez un mouvement de caisse.');}
 if(table==='projects'){ref(s,'clients',d.clientId,'Client');assert(Number(d.contractAmount)>=0&&Number(d.budget)>=0,'Montants invalides.');}
 if(table==='expenses'){amount(d.amount);ref(s,'accounts',d.accountId,'Caisse');if(d.scope==='Chantier')ref(s,'projects',d.projectId,'Chantier');else d.projectId='';assert(d.description?.trim(),'Désignation obligatoire.');assert(!find(s,table,id),'Annulez la dépense puis ressaisissez-la pour conserver la trace.');}
 if(table==='quotes'){docCheck(s,d);assert(!find(s,'quotes',id)?.invoiceId,'Un devis facturé ne peut plus être modifié.');d.number=d.number||nextNumber(s,'quotes',s.settings.quotePrefix);}
 if(table==='tasks'){ref(s,'employees',d.employeeId,'Membre');ref(s,'projects',d.projectId,'Chantier');amount(d.agreedAmount);assert(Number(d.agreedAmount)>=sum(active(s.teamPayments).filter(x=>x.taskId===id)),'Le montant convenu est inférieur aux paiements déjà versés.');}
 if(table==='materials'){assert(d.description?.trim(),'Désignation obligatoire.');assert(Number(d.opening)>=0&&Number(d.threshold)>=0&&Number(d.lastPrice)>=0,'Valeurs négatives interdites.');if(find(s,table,id))assert(Number(d.opening)===Number(find(s,table,id).opening),'Le stock initial est figé. Utilisez une entrée ou sortie.');}
 if(table==='orders'){ref(s,'suppliers',d.supplierId,'Fournisseur');assert(d.description?.trim(),'Désignation obligatoire.');amount(d.amount);d.number=d.number||nextNumber(s,'orders','GBA-BC');d.status=d.status||'À commander';}
 if(table==='journal'){ref(s,'projects',d.projectId,'Chantier');assert(d.note?.trim(),'La note est obligatoire.');}
 if(table==='schedules'){ref(s,'invoices',d.invoiceId,'Facture');amount(d.amount);assert(d.dueDate,'Date obligatoire.');assert(sum(s.schedules.filter(x=>x.invoiceId===d.invoiceId&&x.id!==id))+Number(d.amount)<=docTotal(find(s,'invoices',d.invoiceId)),'Les échéances dépassent le total facturé.');}
 if(table==='attachments'){assert(d.name&&/^data:(image\/(png|jpeg|webp)|application\/pdf);base64,/.test(d.url),'Image PNG/JPEG/WebP ou PDF requis.');assert(d.url.length<1500000,'Pièce jointe trop volumineuse (1 Mo maximum).');}
 let pos=s[table].findIndex(x=>x.id===id);if(pos<0)s[table].push(d);else s[table][pos]=d;
 }
 else if(type==='invoice') {docCheck(s,data);s.invoices.push({...data,id,number:nextNumber(s,'invoices',s.settings.invoicePrefix),status:'Envoyée'});}
 else if(type==='convert'){const q=find(s,'quotes',action.id);assert(q,'Devis introuvable.');assert(!q.invoiceId,'Ce devis possède déjà une facture.');docCheck(s,q);id=uid();s.invoices.push({...q,id,quoteId:q.id,date:today(),number:nextNumber(s,'invoices',s.settings.invoicePrefix),status:'Envoyée'});q.invoiceId=id;q.status='Facturé';}
 else if(type==='projectFromDocument'){const n=apply(s,{type:'save',table:'projects',data});return apply(n,{type:'linkProject',table:data.sourceTable,id:data.sourceId,data:{projectId:id}});}
 else if(type==='linkProject'){assert(['quotes','invoices'].includes(table),'Document invalide.');const d=find(s,table,action.id);assert(d&&!d.void,'Document introuvable.');ref(s,'projects',data.projectId,'Chantier');assert(find(s,'projects',data.projectId).clientId===d.clientId,'Le chantier doit appartenir au client.');assert(!d.projectId,'Ce document est déjà lié à un chantier.');d.projectId=data.projectId;if(table==='invoices'){s.payments.filter(p=>p.invoiceId===d.id).forEach(p=>p.projectId=data.projectId);const q=find(s,'quotes',d.quoteId);if(q&&!q.projectId)q.projectId=data.projectId;}if(table==='quotes'&&d.invoiceId){let i=find(s,'invoices',d.invoiceId);if(i){i.projectId=data.projectId;s.payments.filter(p=>p.invoiceId===i.id).forEach(p=>p.projectId=data.projectId);}}}
 else if(type==='payment'){let i=find(s,'invoices',data.invoiceId);assert(i&&!i.void,'Facture introuvable ou annulée.');ref(s,'accounts',data.accountId,'Caisse');amount(data.amount);assert(Number(data.amount)<=due(s,i),'Le paiement dépasse le reste à encaisser.');s.payments.push({...data,id,amount:Number(data.amount),clientId:i.clientId,projectId:i.projectId,number:nextNumber(s,'payments',s.settings.receiptPrefix)});}
 else if(type==='teamPayment'){let t=find(s,'tasks',data.taskId);assert(t,'Choisissez une tâche.');ref(s,'accounts',data.accountId,'Caisse');amount(data.amount);assert(Number(data.amount)<=Number(t.agreedAmount)-sum(active(s.teamPayments).filter(x=>x.taskId===t.id)),'Le paiement dépasse le solde de la tâche.');s.teamPayments.push({...data,id,amount:Number(data.amount),employeeId:t.employeeId,projectId:t.projectId});}
 else if(type==='transfer'){ref(s,'accounts',data.fromId,'Caisse source');ref(s,'accounts',data.toId,'Caisse destination');assert(data.fromId!==data.toId,'Choisissez deux caisses différentes.');amount(data.amount);assert(Number(data.amount)<=balance(s,data.fromId),'Solde insuffisant dans la caisse source.');s.transfers.push({...data,id,amount:Number(data.amount)});}
 else if(type==='cash'){ref(s,'accounts',data.accountId,'Caisse');assert(Number.isSafeInteger(Number(data.amount))&&Number(data.amount)!==0,'Montant signé non nul requis.');assert(data.label?.trim(),'Le motif est obligatoire.');s.cashEntries.push({...data,id,amount:Number(data.amount)});}
 else if(type==='stock'){ref(s,'materials',data.materialId,'Matériau');assert(Number(data.quantity)>0&&Number.isFinite(Number(data.quantity)),'Quantité invalide.');assert(['Entrée','Sortie'].includes(data.type),'Type invalide.');if(data.type==='Sortie')assert(stock(s,data.materialId)>=Number(data.quantity),'Stock insuffisant.');s.stockMoves.push({...data,id,quantity:Number(data.quantity)});}
 else if(type==='delivery'){const o=find(s,'orders',data.orderId);assert(o&&o.status!=='Reçu','Commande introuvable ou déjà réceptionnée.');s.deliveries.push({...data,id,number:nextNumber(s,'deliveries','GBA-BL'),supplierId:o.supplierId,projectId:o.projectId});o.status='Reçu';}
 else if(type==='void'){assert(['expenses','payments','invoices','teamPayments','transfers','cashEntries'].includes(table),'Annulation non autorisée.');let x=find(s,table,action.id);assert(x&&!x.void,'Écriture introuvable ou déjà annulée.');if(table==='invoices')assert(paid(s,x.id)===0,'Annulez les paiements avant la facture.');assert(action.reason?.trim(),'Motif d’annulation obligatoire.');x.void=true;x.voidReason=action.reason;}
 else if(type==='settings'){s.settings={...s.settings,...data};}
 else throw Error('Action inconnue.');
 s.audit.push({id:uid(),date:new Date().toISOString(),type,table:table||type,entityId:id,reason:action.reason||''});s.updatedAt=new Date().toISOString();return s;
}
export function validate(s){assert(s&&s.schema===3&&s.app==='GBA Gestion Web','Ce fichier n’est pas une sauvegarde GBA Web compatible.');for(const t of TABLES){assert(Array.isArray(s[t]),'Table manquante : '+t);let ids=new Set();for(const x of s[t]){assert(x&&typeof x.id==='string'&&!ids.has(x.id),'Identifiants invalides : '+t);ids.add(x.id);for(const k of ['amount','opening','budget','contractAmount','agreedAmount','quantity','lastPrice','threshold'])if(x[k]!=null)assert(Number.isFinite(Number(x[k])),'Valeur invalide : '+t);}}
 assert(s.settings&&s.accounts.length,'Paramètres ou caisses manquants.');for(const i of s.invoices){docCheck(s,i);assert(paid(s,i.id)<=docTotal(i),'Paiements supérieurs à la facture.');}for(const p of s.payments){ref(s,'invoices',p.invoiceId,'Facture');ref(s,'accounts',p.accountId,'Caisse');amount(p.amount);}for(const t of s.transfers){ref(s,'accounts',t.fromId,'Caisse');ref(s,'accounts',t.toId,'Caisse');amount(t.amount);assert(t.fromId!==t.toId,'Transfert invalide.');}for(const a of s.attachments)assert(/^data:(image\/(png|jpeg|webp)|application\/pdf);base64,/.test(a.url),'Pièce jointe non autorisée.');for(const p of s.projects)if(p.clientId)ref(s,'clients',p.clientId,'Client');for(const q of s.quotes)docCheck(s,q);
 for(const e of s.expenses){ref(s,'accounts',e.accountId,'Caisse');amount(e.amount);if(e.scope==='Chantier')ref(s,'projects',e.projectId,'Chantier');}
 for(const t of s.tasks){ref(s,'employees',t.employeeId,'Membre');ref(s,'projects',t.projectId,'Chantier');amount(t.agreedAmount);assert(sum(active(s.teamPayments).filter(p=>p.taskId===t.id))<=t.agreedAmount,'Paiements équipe supérieurs à la tâche.');}
 for(const p of s.teamPayments){ref(s,'tasks',p.taskId,'Tâche');ref(s,'accounts',p.accountId,'Caisse');amount(p.amount);}
 for(const p of s.cashEntries){ref(s,'accounts',p.accountId,'Caisse');assert(Number.isSafeInteger(p.amount)&&p.amount!==0,'Mouvement de caisse invalide.');}
 for(const m of s.stockMoves){ref(s,'materials',m.materialId,'Matériau');assert(Number(m.quantity)>0&&['Entrée','Sortie'].includes(m.type),'Mouvement de stock invalide.');}
 for(const e of s.schedules){ref(s,'invoices',e.invoiceId,'Facture');amount(e.amount);}
 return s;}
export function demo(){let s=empty();s.demo=true;s.clients=[{id:'c1',name:'M. Sidibé',phone:'',address:'Bamako'}];s.projects=[{id:'p1',name:'Villa — M. Sidibé',clientId:'c1',contractAmount:5200000,budget:3500000,status:'En cours',startDate:today()}];s.invoices=[{id:'i1',number:'GBA-F-2026-001',clientId:'c1',projectId:'p1',date:today(),dueDate:today(),lines:[{description:'Aménagement intérieur',quantity:1,unit:'forfait',unitPrice:5200000}],tax:0,discount:0}];s.payments=[{id:'pay1',invoiceId:'i1',clientId:'c1',projectId:'p1',accountId:'main',amount:4000000,date:today(),number:'GBA-R-2026-001',method:'Virement'}];s.expenses=[{id:'e1',description:'Matériaux et fournitures',amount:875000,scope:'Chantier',projectId:'p1',accountId:'main',date:today(),category:'Matériaux'}];return s;}
