import{empty,validate,docTotal,sum,balance,uid}from'./domain.js';
const camel=k=>k.replace(/_([a-z])/g,(_,x)=>x.toUpperCase());
export function importAndroid(raw){if(raw?.app!=='GBA Gestion'||!Array.isArray(raw.clients)||!Array.isArray(raw.invoices)||!Array.isArray(raw.cash_transactions))throw Error('Sauvegarde Android GBA complète requise.');const s=empty(),warnings=[];const rows=t=>(raw[t]||[]).filter(r=>!r.deleted);const mapped=t=>rows(t).map(r=>Object.fromEntries(Object.entries(r).filter(([k])=>!['sync_dirty','global_id','deleted','updated_at'].includes(k)).map(([k,v])=>[camel(k),k==='id'||k.endsWith('_id')?v==null?'':String(v):v])));
 for(const t of ['clients','projects','employees','suppliers','materials'])s[t]=mapped(t);s.projects.forEach(x=>x.budget=Number(x.budget)||0);s.materials.forEach(x=>{x.opening=0;x.threshold=0});
 s.tasks=mapped('employee_tasks');s.teamPayments=mapped('employee_payments').map(x=>({...x,accountId:'main',method:x.paymentMethod}));s.expenses=mapped('expenses').map(x=>({...x,scope:({PROJECT:'Chantier',COMPANY:'Entreprise',PERSONAL:'Personnel'})[x.scope]||x.scope,accountId:'main',method:x.paymentMethod}));
 for(const t of ['quotes','invoices']){s[t]=mapped(t).map(d=>{const lineTable=t==='quotes'?'quote_items':'invoice_items',foreign=t==='quotes'?'quote_id':'invoice_id';let lines=rows(lineTable).filter(l=>String(l[foreign])===d.id).map(l=>({description:l.description,quantity:Number(l.quantity),unit:l.unit,unitPrice:Number(l.unit_price)}));if(!lines.length)lines=[{description:d.subject||d.description||'Reprise document Android',quantity:1,unit:'forfait',unitPrice:Number(d.total)}];const v={...d,lines,tax:0,discount:0,void:d.status==='Annulée'};if(docTotal(v)!==Number(d.total))throw Error('Total des lignes différent du total enregistré pour '+d.number+'. Vérification manuelle requise.');return v});}
 s.payments=mapped('client_payments').map(p=>({...p,accountId:'main',number:p.receiptNo||'REPRISE-'+p.id,method:p.paymentMethod}));
 for(const i of s.invoices){const old=rows('invoices').find(x=>String(x.id)===i.id),recorded=sum(s.payments.filter(p=>p.invoiceId===i.id));if(recorded!==Number(old.paid))throw Error('Paiements incohérents pour '+i.number+'. Import interrompu pour préserver les comptes.');}
 s.schedules=mapped('payment_schedules');s.cashEntries=mapped('cash_transactions').filter(x=>['Apport caisse','Retrait caisse'].includes(x.type)).map(x=>({...x,accountId:'main'}));
 const oldBalance=sum(rows('cash_transactions'));s.accounts[0].opening=oldBalance-balance(s,'main');if(s.accounts[0].opening!==0)warnings.push('Solde initial de rapprochement : '+s.accounts[0].opening+' F. Toutes les écritures reprises sont regroupées dans Caisse entreprise ; vérifier les anciennes sources de financement.');
 const conf=mapped('company_settings')[0];if(conf){for(const k of Object.keys(s.settings))if(conf[k]!=null)s.settings[k]=conf[k];}
 if(rows('accounting_attachments').length)warnings.push(rows('accounting_attachments').length+' pièces Android à joindre à nouveau : les fichiers du téléphone ne sont pas contenus dans le JSON.');
 warnings.push('Vérifier les devis déjà convertis avant une nouvelle conversion : V2 ne conservait pas de lien explicite devis/facture.');
 s.legacyArchive={schemaVersion:raw.schema_version,materialPriceHistory:raw.material_price_history||[],reminders:raw.reminders||[],attachmentReferences:raw.accounting_attachments||[],cashTransactions:raw.cash_transactions||[]};s.importReport={source:'Android V2',at:new Date().toISOString(),warnings};s.audit.push({id:uid(),date:new Date().toISOString(),type:'Import Android',table:'audit',reason:warnings.join(' ')});return {data:validate(s),warnings};}
